# Generated by Django 4.2.10 on 2024-04-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('Movie_Title', models.CharField(max_length=250)),
                ('Poster', models.ImageField(upload_to='image')),
                ('Description', models.TextField()),
                ('Release_date', models.DateField()),
                ('Actors', models.TextField()),
                ('Trailer', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='place',
        ),
    ]
