# Generated by Django 4.2.10 on 2024-04-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_delete_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Movie_Title',
            new_name='Movie_Name',
        ),
    ]
