# Generated by Django 4.2.10 on 2024-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_rename_movie_title_movie_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Trailer',
            field=models.TextField(),
        ),
    ]
