# Generated by Django 4.2.10 on 2024-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
