# Generated by Django 4.2.10 on 2024-04-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Trailer',
            field=models.IntegerField(),
        ),
    ]
